org.gradle.jvmargs=-Xmx1G
org.gradle.java.installations.fromEnv=JDK21,JDK25

# Mod Properties
mod_id=spreadspawnpoints
mod_name=Spread Spawnpoints
mod_description=Spread all new players around the world in various ways

version=1.3.0-26.2

# Publishing
maven_group=xyz.verarr
archives_base_name=spreadspawnpoints

release_type=STABLE
modrinth_project_id=NSuTfWct
# github_repository=example/example
# git_branch=main
