package xyz.verarr.spreadspawnpoints.spawnpoints;

import java.util.function.Consumer;
import java.util.function.Function;

import net.minecraft.core.MappedRegistry;
import net.minecraft.core.Registry;
import net.minecraft.resources.Identifier;
import net.minecraft.resources.ResourceKey;
import net.minecraft.server.level.ServerLevel;

import com.mojang.serialization.Codec;
import com.mojang.serialization.Decoder;
import com.mojang.serialization.Lifecycle;

import org.joml.Vector2i;
import xyz.verarr.spreadspawnpoints.SpreadSpawnPoints;

public interface SpawnPointGenerator {
    record SpawnPointGeneratorType<T extends SpawnPointGenerator>(
        Function<ServerLevel, Codec<T>> codecFactory,
        Decoder<Consumer<T>>            partialDecoder,
        Function<ServerLevel, T>        constructor) {
        public static final ResourceKey<Registry<SpawnPointGeneratorType<?>>> REGISTRY_KEY =
            ResourceKey.createRegistryKey(
                Identifier.fromNamespaceAndPath(SpreadSpawnPoints.MOD_ID, "generator"));

        public static final Registry<SpawnPointGeneratorType<?>> REGISTRY =
            new MappedRegistry<>(REGISTRY_KEY, Lifecycle.stable());

        public static <T extends SpawnPointGenerator> SpawnPointGeneratorType<T> register(
            Identifier id, SpawnPointGeneratorType<T> type) {
            return Registry.register(REGISTRY, id, type);
        }
    }

    SpawnPointGeneratorType<?> getType();

    /**
     * Generate a new spawnpoint and return it.
     *
     * @return the generated spawnpoint coordinates.
     */
    Vector2i next();

    /**
     * Test if a spawnpoint is valid, as in it may be generated by this generator.
     *
     * @param spawnPoint spawnpoint to test
     * @return true if the spawnpoint may be generated by this generator, false otherwise.
     */
    boolean isValid(Vector2i spawnPoint);

    /**
     * Internal method to add a spawnpoint to the generator. Only use this if necessary.
     * <p>
     * Implementations may ignore this method.
     *
     * @param spawnPoint spawnpoint to add
     */
    void add(Vector2i spawnPoint);

    /**
     * Internal method to remove a spawnpoint from the generator. Only use this if necessary.
     * <p>
     * Implementations may ignore this method.
     *
     * @param spawnPoint spawnpoint to remove
     */
    void remove(Vector2i spawnPoint);
}
