package xyz.verarr.spreadspawnpoints.spawnpoints.generators;

import java.util.Optional;
import java.util.function.Consumer;

import org.jetbrains.annotations.Contract;

import net.minecraft.core.BlockPos;
import net.minecraft.resources.Identifier;
import net.minecraft.server.level.ServerLevel;

import com.mojang.serialization.Codec;
import com.mojang.serialization.Decoder;
import com.mojang.serialization.codecs.RecordCodecBuilder;

import org.joml.Vector2i;
import xyz.verarr.spreadspawnpoints.SpreadSpawnPoints;
import xyz.verarr.spreadspawnpoints.spawnpoints.SpawnPointGenerator;

public class GridSpawnPointGenerator implements SpawnPointGenerator {
    public final Vector2i gridSize = new Vector2i(16);
    public final Vector2i offset   = new Vector2i(0);

    private int currentX                = 0;
    private int currentY                = 0;
    private int direction               = 0;  // 0: right, 1: down, 2: left, 3: up
    private int stepsInCurrentDirection = 0;
    private int stepsInCurrentLayer     = 1;

    /**
     * Generate a new spawnpoint and return it.
     *
     * @return the generated spawnpoint coordinates.
     */
    @Override
    public Vector2i next() {
        Vector2i vector = new Vector2i(currentX, currentY).mul(gridSize).add(offset);
        moveToNext();
        return vector;
    }

    /**
     * Spiral pattern algorithm
     */
    @Contract(mutates = "this")
    private void moveToNext() {
        switch (direction) {
        case 0:  // Move right
            currentX++;
            break;
        case 1:  // Move down
            currentY++;
            break;
        case 2:  // Move left
            currentX--;
            break;
        case 3:  // Move up
            currentY--;
            break;
        }

        stepsInCurrentDirection++;

        // Check if we need to change direction
        if (stepsInCurrentDirection == stepsInCurrentLayer) {
            direction               = (direction + 1) % 4;  // Change direction
            stepsInCurrentDirection = 0;

            // Increase the layer size after completing two directions
            if (direction == 0 || direction == 2) { stepsInCurrentLayer++; }
        }
    }

    /**
     * Test if a spawnpoint is valid, as in it may be generated by this generator.
     *
     * @param spawnPoint spawnpoint to test
     * @return true if the spawnpoint may be generated by this generator, false otherwise.
     */
    @Override
    public boolean isValid(Vector2i spawnPoint) {
        return ((spawnPoint.x - offset.x) % gridSize.x == 0
                && (spawnPoint.y - offset.y) % gridSize.y == 0);
    }

    /**
     * This method is ignored.
     */
    @Override
    public void add(Vector2i spawnPoint) { }

    /**
     * This method is ignored.
     */
    @Override
    public void remove(Vector2i spawnPoint) { }

    // Serialization
    @Override
    public SpawnPointGeneratorType<?> getType() {
        return TYPE;
    }

    private static final Codec<GridSpawnPointGenerator> CODEC = RecordCodecBuilder.create(
        instance
        -> instance
               .group(Codec.INT.fieldOf("gridX").forGetter(gen -> gen.gridSize.x),
                      Codec.INT.fieldOf("gridZ").forGetter(gen -> gen.gridSize.y),
                      Codec.INT.fieldOf("offsetX").forGetter(gen -> gen.offset.x),
                      Codec.INT.fieldOf("offsetZ").forGetter(gen -> gen.offset.y),
                      Codec.INT.fieldOf("currentX").forGetter(gen -> gen.currentX),
                      Codec.INT.fieldOf("currentZ").forGetter(gen -> gen.currentY),
                      Codec.INT.fieldOf("direction").forGetter(gen -> gen.direction),
                      Codec.INT.fieldOf("stepsInCurrentDirection")
                          .forGetter(gen -> gen.stepsInCurrentDirection),
                      Codec.INT.fieldOf("stepsInCurrentLayer")
                          .forGetter(gen -> gen.stepsInCurrentLayer))
               .apply(instance, GridSpawnPointGenerator::new));

    /// From-parts constructor
    private GridSpawnPointGenerator(int gridX,
                                    int gridZ,
                                    int offsetX,
                                    int offsetZ,
                                    int currentX,
                                    int currentY,
                                    int direction,
                                    int stepsInCurrentDirection,
                                    int stepsInCurrentLayer) {
        this.gridSize.x              = gridX;
        this.gridSize.y              = gridZ;
        this.offset.x                = offsetX;
        this.offset.y                = offsetZ;
        this.currentX                = currentX;
        this.currentY                = currentY;
        this.direction               = direction;
        this.stepsInCurrentDirection = stepsInCurrentDirection;
        this.stepsInCurrentLayer     = stepsInCurrentLayer;
    };

    private static final Decoder<Consumer<GridSpawnPointGenerator>> PARTIAL_DECODER =
        StrictCodecUtils
            .strict(RecordCodecBuilder.<Consumer<GridSpawnPointGenerator>>mapCodec(
                instance
                -> instance
                       .group(Codec.INT.optionalFieldOf("gridX").forGetter(_ -> Optional.empty()),
                              Codec.INT.optionalFieldOf("gridZ").forGetter(_ -> Optional.empty()),
                              Codec.INT.optionalFieldOf("offsetX").forGetter(_ -> Optional.empty()),
                              Codec.INT.optionalFieldOf("offsetZ").forGetter(_ -> Optional.empty()))
                       .apply(instance,
                              (gridX, gridZ, offsetX, offsetZ) -> gen -> {
                                  gridX.ifPresent(v -> gen.gridSize.x = v);
                                  gridZ.ifPresent(v -> gen.gridSize.y = v);
                                  offsetX.ifPresent(v -> gen.offset.x = v);
                                  offsetZ.ifPresent(v -> gen.offset.y = v);
                              })))
            .codec();

    public static SpawnPointGeneratorType<?> TYPE = SpawnPointGeneratorType.register(
        Identifier.fromNamespaceAndPath(SpreadSpawnPoints.MOD_ID, "grid"),
        new SpawnPointGeneratorType<>(_ -> CODEC, PARTIAL_DECODER, GridSpawnPointGenerator::new));

    /// Default constructor
    public GridSpawnPointGenerator(ServerLevel serverLevel) {
        BlockPos worldSpawn = serverLevel.getRespawnData().pos();
        this.offset.set(worldSpawn.getX(), worldSpawn.getZ());
    }
}
