package xyz.verarr.spreadspawnpoints.spawnpoints.generators;

import java.util.Optional;
import java.util.function.Consumer;

import net.minecraft.resources.Identifier;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.util.RandomSource;
import net.minecraft.world.level.border.WorldBorder;
import net.minecraft.world.level.levelgen.LegacyRandomSource;

import com.mojang.serialization.Codec;
import com.mojang.serialization.Decoder;
import com.mojang.serialization.codecs.RecordCodecBuilder;

import org.joml.Vector2i;
import xyz.verarr.spreadspawnpoints.SpreadSpawnPoints;
import xyz.verarr.spreadspawnpoints.mixin.LegacyRandomSourceAccessor;
import xyz.verarr.spreadspawnpoints.spawnpoints.SpawnPointGenerator;

public class RandomSpawnPointGenerator implements SpawnPointGenerator {
    private final Vector2i     lowerBounds;
    private final Vector2i     upperBounds;
    private final RandomSource random;

    /**
     * Generate a new spawnpoint and return it.
     *
     * @return the generated spawnpoint coordinates.
     */
    @Override
    public Vector2i next() {
        return new Vector2i(random.nextIntBetweenInclusive(lowerBounds.x, upperBounds.x),
                            random.nextIntBetweenInclusive(lowerBounds.y, upperBounds.y));
    }

    /**
     * Test if a spawnpoint is valid, as in it may be generated by this generator.
     *
     * @param spawnPoint spawnpoint to test
     * @return true if the spawnpoint may be generated by this generator, false otherwise.
     */
    @Override
    public boolean isValid(Vector2i spawnPoint) {
        return (lowerBounds.x <= spawnPoint.x && upperBounds.x >= spawnPoint.x
                && lowerBounds.y <= spawnPoint.y && upperBounds.y >= spawnPoint.y);
    }

    /**
     * This method is ignored.
     */
    @Override
    public void add(Vector2i spawnPoint) { }

    /**
     * This method is ignored.
     */
    @Override
    public void remove(Vector2i spawnPoint) { }

    // Serialization
    @Override
    public SpawnPointGeneratorType<?> getType() {
        return TYPE;
    }

    private static final Codec<RandomSpawnPointGenerator> CODEC = RecordCodecBuilder.create(
        instance
        -> instance
               .group(Codec.INT.fieldOf("lowerX").forGetter(gen -> gen.lowerBounds.x),
                      Codec.INT.fieldOf("lowerZ").forGetter(gen -> gen.lowerBounds.y),
                      Codec.INT.fieldOf("upperX").forGetter(gen -> gen.upperBounds.x),
                      Codec.INT.fieldOf("upperZ").forGetter(gen -> gen.upperBounds.y),
                      Codec.LONG.fieldOf("seed").forGetter(
                          gen -> ((LegacyRandomSourceAccessor) (gen.random)).getSeed().get()))
               .apply(instance, RandomSpawnPointGenerator::new));

    /// From-parts constructor
    private RandomSpawnPointGenerator(int lowerX, int lowerZ, int upperX, int upperZ, long seed) {
        this.lowerBounds = new Vector2i(lowerX, lowerZ);
        this.upperBounds = new Vector2i(upperX, upperZ);
        this.random      = new LegacyRandomSource(seed);
    };

    private static final Decoder<Consumer<RandomSpawnPointGenerator>> PARTIAL_DECODER =
        StrictCodecUtils
            .strict(RecordCodecBuilder.<Consumer<RandomSpawnPointGenerator>>mapCodec(
                instance
                -> instance
                       .group(Codec.INT.optionalFieldOf("lowerX").forGetter(_ -> Optional.empty()),
                              Codec.INT.optionalFieldOf("lowerZ").forGetter(_ -> Optional.empty()),
                              Codec.INT.optionalFieldOf("upperX").forGetter(_ -> Optional.empty()),
                              Codec.INT.optionalFieldOf("upperZ").forGetter(_ -> Optional.empty()),
                              Codec.LONG.optionalFieldOf("seed").forGetter(_ -> Optional.empty()))
                       .apply(instance,
                              (lowerX, lowerZ, upperX, upperZ, seed) -> gen -> {
                                  lowerX.ifPresent(v -> gen.lowerBounds.x = v);
                                  lowerZ.ifPresent(v -> gen.lowerBounds.y = v);
                                  upperX.ifPresent(v -> gen.upperBounds.x = v);
                                  upperZ.ifPresent(v -> gen.upperBounds.y = v);
                                  seed.ifPresent(gen.random::setSeed);
                              })))
            .codec();

    public static SpawnPointGeneratorType<?> TYPE = SpawnPointGeneratorType.register(
        Identifier.fromNamespaceAndPath(SpreadSpawnPoints.MOD_ID, "random"),
        new SpawnPointGeneratorType<>(_ -> CODEC, PARTIAL_DECODER, RandomSpawnPointGenerator::new));

    /// Default constructor
    public RandomSpawnPointGenerator(ServerLevel serverLevel) {
        WorldBorder border = serverLevel.getWorldBorder();
        this.lowerBounds   = new Vector2i((int) border.getMinX(), (int) border.getMinZ());
        this.upperBounds   = new Vector2i((int) border.getMaxX(), (int) border.getMaxZ());
        this.random        = new LegacyRandomSource(serverLevel.getSeed());
    }
}
