package xyz.verarr.spreadspawnpoints.spawnpoints.generators;

import java.util.*;
import java.util.function.Consumer;
import java.util.stream.Stream;

import org.jetbrains.annotations.NotNull;

import net.minecraft.core.BlockPos;
import net.minecraft.resources.Identifier;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.world.level.border.WorldBorder;
import net.minecraft.world.level.levelgen.LegacyRandomSource;

import com.mojang.serialization.Codec;
import com.mojang.serialization.Decoder;
import com.mojang.serialization.codecs.RecordCodecBuilder;

import org.joml.Vector2i;
import xyz.verarr.spreadspawnpoints.SpreadSpawnPoints;
import xyz.verarr.spreadspawnpoints.mixin.LegacyRandomSourceAccessor;
import xyz.verarr.spreadspawnpoints.spawnpoints.SpawnPointGenerator;

public class SpringSpawnPointGenerator implements SpawnPointGenerator {
    private static final int DEFAULT_RESERVE_RADIUS            = 128;
    private static final int DEFAULT_OVERLAP_RADIUS            = 256;
    private static final int DEFAULT_WORLDSPAWN_RESERVE_RADIUS = 256;
    private static final int DEFAULT_WORLDSPAWN_OVERLAP_RADIUS = 256 + 128;
    private static final List<Vector2i> VECTOR_NEIGHBORS       = Arrays.asList(new Vector2i(-1, -1),
                                                                               new Vector2i(-1, 0),
                                                                               new Vector2i(-1, +1),
                                                                               new Vector2i(0, -1),
                                                                               new Vector2i(0, 0),
                                                                               new Vector2i(0, +1),
                                                                               new Vector2i(+1, -1),
                                                                               new Vector2i(+1, 0),
                                                                               new Vector2i(+1, +1));

    // settings
    private final Vector2i worldSpawn;
    private final Vector2i lowerBounds;
    private final Vector2i upperBounds;
    private int            reserveRadius           = DEFAULT_RESERVE_RADIUS;
    private int            overlapRadius           = DEFAULT_OVERLAP_RADIUS;
    private int            worldspawnReserveRadius = DEFAULT_WORLDSPAWN_RESERVE_RADIUS;
    private int            worldspawnOverlapRadius = DEFAULT_WORLDSPAWN_OVERLAP_RADIUS;

    // state
    private final LegacyRandomSource     random;
    private Map<Vector2i, Set<Vector2i>> grid                           = new HashMap<>();
    private int                          greatestDistanceFromWorldspawn = 0;

    /**
     * Generate a new spawnpoint and return it.
     *
     * @return the generated spawnpoint coordinates.
     */
    @Override
    public Vector2i next() {
        int lowerX = Math.clamp(-greatestDistanceFromWorldspawn - overlapRadius, lowerBounds.x,
                                worldSpawn.x - worldspawnOverlapRadius);
        int lowerZ = Math.clamp(-greatestDistanceFromWorldspawn - overlapRadius, lowerBounds.y,
                                worldSpawn.y - worldspawnOverlapRadius);
        int upperX = Math.clamp(greatestDistanceFromWorldspawn + overlapRadius,
                                worldSpawn.x + worldspawnOverlapRadius, upperBounds.x);
        int upperZ = Math.clamp(greatestDistanceFromWorldspawn + overlapRadius,
                                worldSpawn.y + worldspawnOverlapRadius, upperBounds.y);

        return new Vector2i(random.nextIntBetweenInclusive(lowerX, upperX),
                            random.nextIntBetweenInclusive(lowerZ, upperZ));
    }

    private Vector2i gridCoordinates(Vector2i worldCoordinates) {
        return new Vector2i(worldCoordinates.x / overlapRadius, worldCoordinates.y / overlapRadius);
    }

    private boolean overlaps(Vector2i a, Vector2i b) { return a.distance(b) < overlapRadius; }

    private boolean conflicts(Vector2i a, Vector2i b) { return a.distance(b) < reserveRadius; }

    private boolean overlapsWithWorldspawn(Vector2i vec) {
        return vec.distance(worldSpawn) < worldspawnOverlapRadius;
    }

    private boolean conflictsWithWorldspawn(Vector2i vec) {
        return vec.distance(worldSpawn) < worldspawnReserveRadius;
    }

    /**
     * Test if a spawnpoint is valid, as in it may be generated by this generator.
     *
     * @param spawnPoint spawnpoint to test
     * @return true if the spawnpoint may be generated by this generator, false
     *         otherwise.
     */
    @Override
    public boolean isValid(Vector2i spawnPoint) {
        if (!(lowerBounds.x <= spawnPoint.x && upperBounds.x >= spawnPoint.x
              && lowerBounds.y <= spawnPoint.y && upperBounds.y >= spawnPoint.y))
            return false;

        boolean overlaps = false;

        if (conflictsWithWorldspawn(spawnPoint)) return false;
        if (overlapsWithWorldspawn(spawnPoint)) overlaps = true;

        List<Vector2i> affectedSpawnPoints = getAffectedSpawnPoints(spawnPoint).toList();
        for (Vector2i affectedSpawnPoint : affectedSpawnPoints) {
            if (conflicts(affectedSpawnPoint, spawnPoint)) return false;
            if (!overlaps && overlaps(affectedSpawnPoint, spawnPoint)) overlaps = true;
        }

        if (!overlaps) return false;

        return true;
    }

    private @NotNull Stream<Vector2i> getAffectedSpawnPoints(Vector2i spawnPoint) {
        return VECTOR_NEIGHBORS.stream()
            .map(vec -> {
                try {
                    return (Vector2i) (vec.clone());
                } catch (CloneNotSupportedException e) { throw new RuntimeException(e); }
            })
            .map(vec -> vec.add(gridCoordinates(spawnPoint)))
            .filter(grid::containsKey)
            .flatMap(gridCoordinates -> grid.get(gridCoordinates).stream());
    }

    /**
     * Internal method to add a spawnpoint to the generator. Only use this if
     * necessary.
     * <p>
     * Implementations may ignore this method.
     *
     * @param spawnPoint spawnpoint to add
     */
    @Override
    public void add(Vector2i spawnPoint) {
        if ((int) spawnPoint.distance(worldSpawn) > greatestDistanceFromWorldspawn)
            greatestDistanceFromWorldspawn = (int) spawnPoint.distance(worldSpawn);
        grid.computeIfAbsent(gridCoordinates(spawnPoint), c -> new HashSet<>()).add(spawnPoint);
    }

    /**
     * Internal method to remove a spawnpoint from the generator. Only use this if
     * necessary.
     * <p>
     * Implementations may ignore this method.
     *
     * @param spawnPoint spawnpoint to remove
     */
    @Override
    public void remove(Vector2i spawnPoint) {
        if (!grid.containsKey(gridCoordinates(spawnPoint))) return;
        grid.get(gridCoordinates(spawnPoint)).remove(spawnPoint);
    }

    // Serialization
    @Override
    public SpawnPointGeneratorType<?> getType() {
        return TYPE;
    }

    private static final Codec<SpringSpawnPointGenerator> CODEC = RecordCodecBuilder.create(
        instance
        -> instance
               .group(Codec.INT.fieldOf("lowerX").forGetter(gen -> gen.lowerBounds.x),
                      Codec.INT.fieldOf("lowerZ").forGetter(gen -> gen.lowerBounds.y),
                      Codec.INT.fieldOf("upperX").forGetter(gen -> gen.upperBounds.x),
                      Codec.INT.fieldOf("upperZ").forGetter(gen -> gen.upperBounds.y),
                      Codec.LONG.fieldOf("seed").forGetter(
                          gen -> ((LegacyRandomSourceAccessor) (gen.random)).getSeed().get()),
                      Codec.INT.fieldOf("reserveRadius").forGetter(gen -> gen.reserveRadius),
                      Codec.INT.fieldOf("overlapRadius").forGetter(gen -> gen.overlapRadius),
                      Codec.INT.fieldOf("worldspawnReserveRadius")
                          .forGetter(gen -> gen.worldspawnReserveRadius),
                      Codec.INT.fieldOf("worldspawnOverlapRadius")
                          .forGetter(gen -> gen.worldspawnOverlapRadius),
                      Codec.INT.fieldOf("worldspawnX").forGetter(gen -> gen.worldSpawn.x),
                      Codec.INT.fieldOf("worldspawnZ").forGetter(gen -> gen.worldSpawn.y))

               .apply(instance, SpringSpawnPointGenerator::new));

    /// From-parts constructor
    private SpringSpawnPointGenerator(int  lowerX,
                                      int  lowerZ,
                                      int  upperX,
                                      int  upperZ,
                                      long seed,
                                      int  reserveRadius,
                                      int  overlapRadius,
                                      int  worldspawnReserveRadius,
                                      int  worldspawnOverlapRadius,
                                      int  worldspawnX,
                                      int  worldspawnZ) {
        this.lowerBounds             = new Vector2i(lowerX, lowerZ);
        this.upperBounds             = new Vector2i(upperX, upperZ);
        this.random                  = new LegacyRandomSource(seed);
        this.reserveRadius           = reserveRadius;
        this.overlapRadius           = overlapRadius;
        this.worldspawnReserveRadius = worldspawnReserveRadius;
        this.worldspawnOverlapRadius = worldspawnOverlapRadius;
        this.worldSpawn              = new Vector2i(worldspawnX, worldspawnZ);
    };

    private static final Decoder<Consumer<SpringSpawnPointGenerator>> PARTIAL_DECODER =
        StrictCodecUtils
            .strict(RecordCodecBuilder.<Consumer<SpringSpawnPointGenerator>>mapCodec(
                instance
                -> instance
                       .group(Codec.INT.optionalFieldOf("lowerX").forGetter(_ -> Optional.empty()),
                              Codec.INT.optionalFieldOf("lowerZ").forGetter(_ -> Optional.empty()),
                              Codec.INT.optionalFieldOf("upperX").forGetter(_ -> Optional.empty()),
                              Codec.INT.optionalFieldOf("upperZ").forGetter(_ -> Optional.empty()),
                              Codec.LONG.optionalFieldOf("seed").forGetter(_ -> Optional.empty()),
                              Codec.INT.optionalFieldOf("reserveRadius")
                                  .forGetter(_ -> Optional.empty()),
                              Codec.INT.optionalFieldOf("overlapRadius")
                                  .forGetter(_ -> Optional.empty()),
                              Codec.INT.optionalFieldOf("worldspawnReserveRadius")
                                  .forGetter(_ -> Optional.empty()),
                              Codec.INT.optionalFieldOf("worldspawnOverlapRadius")
                                  .forGetter(_ -> Optional.empty()),
                              Codec.INT.optionalFieldOf("worldspawnX")
                                  .forGetter(_ -> Optional.empty()),
                              Codec.INT.optionalFieldOf("worldspawnZ")
                                  .forGetter(_ -> Optional.empty()))

                       .apply(instance,
                              (lowerX,
                               lowerZ,
                               upperX,
                               upperZ,
                               seed,
                               reserveRadius,
                               overlapRadius,
                               worldspawnReserveRadius,
                               worldspawnOverlapRadius,
                               worldspawnX,
                               worldspawnZ) -> gen -> {
                                  lowerX.ifPresent(v -> gen.lowerBounds.x = v);
                                  lowerZ.ifPresent(v -> gen.lowerBounds.y = v);
                                  upperX.ifPresent(v -> gen.upperBounds.x = v);
                                  upperZ.ifPresent(v -> gen.upperBounds.y = v);
                                  seed.ifPresent(gen.random::setSeed);
                                  reserveRadius.ifPresent(v -> gen.reserveRadius = v);
                                  overlapRadius.ifPresent(v -> gen.overlapRadius = v);
                                  worldspawnReserveRadius.ifPresent(
                                      v -> gen.worldspawnReserveRadius = v);
                                  worldspawnOverlapRadius.ifPresent(
                                      v -> gen.worldspawnOverlapRadius = v);
                                  worldspawnX.ifPresent(v -> gen.worldSpawn.x = v);
                                  worldspawnZ.ifPresent(v -> gen.worldSpawn.y = v);

                                  overlapRadius.ifPresent(_ -> gen.migrateGrid());
                              })))
            .codec();

    private void migrateGrid() {
        Map<Vector2i, Set<Vector2i>> oldGrid = grid;
        grid                                 = new HashMap<>();
        oldGrid.forEach((gridCoordinates, spawnPoints) -> { spawnPoints.forEach(this::add); });
    }

    public static SpawnPointGeneratorType<?> TYPE = SpawnPointGeneratorType.register(
        Identifier.fromNamespaceAndPath(SpreadSpawnPoints.MOD_ID, "spring"),
        new SpawnPointGeneratorType<>(_ -> CODEC, PARTIAL_DECODER, SpringSpawnPointGenerator::new));

    /// Default constructor
    public SpringSpawnPointGenerator(ServerLevel serverLevel) {
        WorldBorder border = serverLevel.getWorldBorder();
        this.lowerBounds   = new Vector2i((int) border.getMinX(), (int) border.getMinZ());
        this.upperBounds   = new Vector2i((int) border.getMaxX(), (int) border.getMaxZ());
        this.random        = new LegacyRandomSource(serverLevel.getSeed());

        BlockPos worldSpawn = serverLevel.getRespawnData().pos();
        this.worldSpawn     = new Vector2i(worldSpawn.getX(), worldSpawn.getZ());
    }
}
