package xyz.verarr.spreadspawnpoints.spawnpoints.generators;

import java.util.function.Consumer;

import net.minecraft.core.BlockPos;
import net.minecraft.resources.Identifier;
import net.minecraft.server.level.ServerLevel;

import com.mojang.datafixers.util.Unit;
import com.mojang.serialization.Codec;
import com.mojang.serialization.Decoder;

import org.joml.Vector2i;
import xyz.verarr.spreadspawnpoints.SpreadSpawnPoints;
import xyz.verarr.spreadspawnpoints.spawnpoints.SpawnPointGenerator;

public class VanillaSpawnPointGenerator implements SpawnPointGenerator {
    private final ServerLevel serverLevel;

    /**
     * Generate a new spawnpoint and return it.
     *
     * @return the generated spawnpoint coordinates.
     */
    @Override
    public Vector2i next() {
        BlockPos spawnPoint = serverLevel.getRespawnData().pos();
        return new Vector2i(spawnPoint.getX(), spawnPoint.getZ());
    }

    /**
     * Test if a spawnpoint is valid, as in it may be generated by this generator.
     *
     * @param spawnPoint spawnpoint to test
     * @return true if the spawnpoint may be generated by this generator, false otherwise.
     */
    @Override
    public boolean isValid(Vector2i spawnPoint) {
        BlockPos worldSpawnPoint = serverLevel.getRespawnData().pos();
        return (spawnPoint.x == worldSpawnPoint.getX() && spawnPoint.y == worldSpawnPoint.getZ());
    }

    /**
     * This method is ignored.
     */
    @Override
    public void add(Vector2i spawnPoint) { }

    /**
     * This method is ignored.
     */
    @Override
    public void remove(Vector2i spawnPoint) { }

    // Serialization
    @Override
    public SpawnPointGeneratorType<?> getType() {
        return TYPE;
    }

    private static Codec<VanillaSpawnPointGenerator> getCodec(ServerLevel level) {
        return Codec.EMPTY.xmap(_ -> new VanillaSpawnPointGenerator(level), _ -> Unit.INSTANCE)
            .codec();
    }

    private static final Decoder<Consumer<VanillaSpawnPointGenerator>> PARTIAL_DECODER =
        Codec.EMPTY.map(_ -> (Consumer<VanillaSpawnPointGenerator>) _ -> {}).decoder();

    public static SpawnPointGeneratorType<?> TYPE = SpawnPointGeneratorType.register(
        Identifier.fromNamespaceAndPath(SpreadSpawnPoints.MOD_ID, "vanilla"),
        new SpawnPointGeneratorType<>(VanillaSpawnPointGenerator::getCodec,
                                      PARTIAL_DECODER,
                                      VanillaSpawnPointGenerator::new));

    /// Default constructor
    public VanillaSpawnPointGenerator(ServerLevel serverLevel) { this.serverLevel = serverLevel; }
}
